---
title: "MainProcess"
author: "dhyanesh babu"
date: "May 6, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# To load the data file and extract the bigram , trigram features

#load the libraries

```{r}
library(R.utils)
library(dplyr)
library(parallel)
library(tm)
library(ggplot2)
library(RWeka)
library(wordcloud)
```

#load the file 

```{r}

twitter_file <- file("C:\\Users\\home\\Documents\\Coursera-SwiftKey\\final\\en_US\\en_US.twitter.txt", open = "rb")
twitter <- readLines(twitter_file, skipNul = TRUE, encoding="UTF-8")
close(twitter_file)

news_file <- file("C:\\Users\\home\\Documents\\Coursera-SwiftKey\\final\\en_US\\en_US.news.txt", open = "rb")
news <- readLines(news_file, skipNul = TRUE, encoding="UTF-8")
close(news_file)

blogs_file <- file("C:\\Users\\home\\Documents\\Coursera-SwiftKey\\final\\en_US\\en_US.blogs.txt", open = "rb")
blogs <- readLines(blogs_file, skipNul = TRUE, encoding="UTF-8")
close(blogs_file)

Sampled_text <- function(textbody, portion) {
  taking <- sample(1:length(textbody), length(textbody)*portion)
  Sampled_text <- textbody[taking]
  Sampled_text
}

# sampling text files 
set.seed(32324)
portion <- 1/50

Sampled_Twitter <- Sampled_text(twitter, portion)
Sampled_Blog <- Sampled_text(blogs, portion)
Sampled_News <- Sampled_text(news, portion)



```
#write it to sample file

```{r}
Sampled_File <- c(Sampled_Blog, Sampled_News, Sampled_Twitter)

writeLines(Sampled_File, "C:\\Users\\home\\Documents\\DataScienceFolder\\Output\\Sampled_File.txt")

```

#Data cleaning
```{r}
cleansing <- function (text_input) {
  text_input <- tm_map(text_input, content_transformer(tolower))
  text_input <- tm_map(text_input, stripWhitespace)
  text_input <- tm_map(text_input, removePunctuation)
  text_input <- tm_map(text_input, removeNumbers)
  text_input
}

Output_Folder <- VCorpus(DirSource("C:\\Users\\home\\Documents\\DataScienceFolder\\Output", encoding = "UTF-8"))


Output_Folder <- cleansing(Output_Folder)


Ngram_Tokernizer <- function (text_input, n) {
  NgramTokenizer <- function(x) {RWeka::NGramTokenizer(x, RWeka::Weka_control(min = n, max = n))}
  Ngram_Tokernizer <- TermDocumentMatrix(text_input, control = list(tokenizer = NgramTokenizer))
  Ngram_Tokernizer
}
```

# n gram tokenizer

```{r}
  ngram_sorted_df <- function (Ngram_Tokernizer) {
  tdm_ngram_m <- as.matrix(Ngram_Tokernizer)
  tdm_ngram_df <- as.data.frame(tdm_ngram_m)
  colnames(tdm_ngram_df) <- "Count"
  tdm_ngram_df <- tdm_ngram_df[order(-tdm_ngram_df$Count), , drop = FALSE]
  tdm_ngram_df
}

```
#extract the n gram and store in the file

```{r}
# Calculate N-Grams
tdm_1gram <- Ngram_Tokernizer(Output_Folder, 1)
tdm_2gram <- Ngram_Tokernizer(Output_Folder, 2)
tdm_3gram <- Ngram_Tokernizer(Output_Folder, 3)
tdm_4gram <- Ngram_Tokernizer(Output_Folder, 4)


# Extract term-count tables from N-Grams and sort 
tdm_1gram_df <- ngram_sorted_df(tdm_1gram)
tdm_2gram_df <- ngram_sorted_df(tdm_2gram)
tdm_3gram_df <- ngram_sorted_df(tdm_3gram)
tdm_4gram_df <- ngram_sorted_df(tdm_4gram)

# Save data frames into r-compressed files

quadgram <- data.frame(rows=rownames(tdm_4gram_df),count=tdm_4gram_df$Count)
quadgram$rows <- as.character(quadgram$rows)
quadgram_split <- strsplit(as.character(quadgram$rows),split=" ")
quadgram <- transform(quadgram,first = sapply(quadgram_split,"[[",1),second = sapply(quadgram_split,"[[",2),third = sapply(quadgram_split,"[[",3), fourth = sapply(quadgram_split,"[[",4))
quadgram <- data.frame(unigram = quadgram$first,bigram = quadgram$second, trigram = quadgram$third, quadgram = quadgram$fourth, freq = quadgram$count,stringsAsFactors=FALSE)
write.csv(quadgram[quadgram$freq > 1,],"C:\\Users\\home\\Documents\\DataScienceFolder\\Output\\quad_gram.csv",row.names=F)
quadgram <- read.csv("C:\\Users\\home\\Documents\\DataScienceFolder\\Output\\quad_gram.csv",stringsAsFactors = F)
saveRDS(quadgram,"C:\\Users\\home\\Documents\\DataScienceFolder\\Output\\quad_gram.RData")


trigram <- data.frame(rows=rownames(tdm_3gram_df),count=tdm_3gram_df$Count)
trigram$rows <- as.character(trigram$rows)
trigram_split <- strsplit(as.character(trigram$rows),split=" ")
trigram <- transform(trigram,first = sapply(trigram_split,"[[",1),second = sapply(trigram_split,"[[",2),third = sapply(trigram_split,"[[",3))
trigram <- data.frame(unigram = trigram$first,bigram = trigram$second, trigram = trigram$third, freq = trigram$count,stringsAsFactors=FALSE)
write.csv(trigram[trigram$freq > 1,],"C:\\Users\\home\\Documents\\DataScienceFolder\\Output\\tri_gram.csv",row.names=F)
trigram <- read.csv("C:\\Users\\home\\Documents\\DataScienceFolder\\Output\\tri_gram.csv",stringsAsFactors = F)
saveRDS(trigram,"C:\\Users\\home\\Documents\\DataScienceFolder\\Output\\tri_gram.RData")


bigram <- data.frame(rows=rownames(tdm_2gram_df),count=tdm_2gram_df$Count)
bigram$rows <- as.character(bigram$rows)
bigram_split <- strsplit(as.character(bigram$rows),split=" ")
bigram <- transform(bigram,first = sapply(bigram_split,"[[",1),second = sapply(bigram_split,"[[",2))
bigram <- data.frame(unigram = bigram$first,bigram = bigram$second,freq = bigram$count,stringsAsFactors=FALSE)
write.csv(bigram[bigram$freq > 1,],"C:\\Users\\home\\Documents\\DataScienceFolder\\Output\\bi_gram.csv",row.names=F)
bigram <- read.csv("C:\\Users\\home\\Documents\\DataScienceFolder\\Output\\bi_gram.csv",stringsAsFactors = F)
saveRDS(bigram,"C:\\Users\\home\\Documents\\DataScienceFolder\\Output\\bi_gram.RData")


```

